import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// The docs collection is vendored from the repo's docs/ by
// scripts/sync-docs.mjs (the Docker build can't see ../docs). Frontmatter is
// generated by the sync, never hand-written.
const docs = defineCollection({
  loader: glob({ pattern: '*.md', base: './src/content/docs' }),
  schema: z.object({
    title: z.string(),
    order: z.number(),
  }),
});

export const collections = { docs };
